name: Django CI

on:
  push:
    branches: 
      - main
     
  pull_request:
    branches: [main]      

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set environment variables
      run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
  
    - name: Run tests for menu
      run: python restaurant/manage.py test menu

    - name: Run tests for reservations
      run: python restaurant/manage.py test reservations

    - name: Run tests for users
      run: python restaurant/manage.py test users.tests

    - name: Run tests for shopping_cart
      run: python restaurant/manage.py test shopping_cart.tests


  deploy:
          needs: [build]
          runs-on: ubuntu-latest
      
          steps:
          - uses: actions/checkout@v2
      
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
      
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      
          - name: Login to Heroku
            uses: akhileshns/heroku-deploy@v3.12.12
            with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "nanaitaliano"
              heroku_email: "nastiya.levchenko@knu.ua"
      
          - name: Deploy to Heroku
            run: |
              heroku config:set DISABLE_COLLECTSTATIC=0
              git push heroku HEAD:main
